### ISSUE TITLE
[css]怎么让Chrome支持小于12px 的文字

### ISSUE THREAD

**Issue by maginapp** [maginapp/sharing-technology-article#11]

**Comment by maginapp** [comment]
```css
p { 
  font-size:10px;
  transform:scale(0.8);
}
```
